%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: D:\gdialynas\Desktop\My files\Passive rider project\Msc_Jelle_de_hann\Subjective data\Subjectivedata.xlsx
%    Worksheet: Sheet1
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2018/09/18 14:41:42

%% Import the data
[~, ~, raw] = xlsread('D:\gdialynas\Desktop\My files\Passive rider project\Jelle_de_hann_final\General\Subjective data\Subjectivedata.xlsx','Sheet1','A1:Y22');
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};

%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),raw); % Find non-numeric cells
raw(R) = {NaN}; % Replace non-numeric cells

%% Create output variable
Subjectivedata = reshape([raw{:}],size(raw));

%% Clear temporary variables
clearvars raw R;
%% Data analysis
mean=nanmean(Subjectivedata,2);
stdev= sqrt(nansum(abs(Subjectivedata - mean),2));
Nasatlxmeanvector=[mean(4,:),mean(5,:),mean(6,:),mean(7,:),mean(8,:),mean(9,:)];
Nasatlxstd=[stdev(4,:),stdev(5,:),stdev(6,:),stdev(7,:),stdev(8,:),stdev(9,:)];
Discomfortmean=[mean(11,:),mean(13,:),mean(14,:)];
Discomfortstd=[stdev(11,:),stdev(13,:),stdev(14,:)];
Otherquestmean=[mean(16,:),mean(17,:),mean(18,:),mean(19,:),mean(20,:)];
Otherqueststd=[stdev(16,:),stdev(17,:),stdev(18,:),stdev(19,:),stdev(20,:)];
figure(1)
barwitherr(Nasatlxstd,Nasatlxmeanvector);
set(gca,'XTick',[1:6],'XTickLabel',{'Mental demand','Physical demand','Temporal demand','Performance','Effort','Frustration'}); 
%title('NASA RAW-TLX(RTLX)')
ylabel('Score(%)') 
ylim([-4 100])
set(gca,'FontSize',13);
%%
figure(2)
h=barwitherr([Discomfortstd,Otherqueststd],[Discomfortmean,Otherquestmean]);
set(gca,'XTick',[1:8],'XTickLabel',{'Discomfort','Disorientation','Nausea','Cycling realism','Visual deviation','Muscle fatigue','Disturbances','Control Uniformity'}); 
title('Questionnaire')
ylabel('Score(%)')
ylim([-4 100])

%% Bar plots without standard deviation scale ( place same figure number in case you want to change color of previous bar plot)
figure(3)
bar(Nasatlxmeanvector)
set(gca,'XTick',[1:6],'XTickLabel',{'Mental demand','Physical demand','Temporal demand','Performance','Effort','Frustration'});
set(gca,'FontSize',17);
%title('NASA RAW-TLX(RTLX)')
ylabel('Score(%)') 
ylim([0 100])
%% figure(4)
h=[Discomfortmean,Otherquestmean];
hold on
bar([1], h(1),'FaceColor','c');
bar([2], h(2),'FaceColor','c');
bar([3], h(3),'FaceColor','c');
bar([4], h(4),'FaceColor','b');
bar([5], h(5),'FaceColor','b');
bar([6], h(6),'FaceColor','b');
bar([7], h(7),'FaceColor','b');
bar([8], h(8),'FaceColor','b');
title('Questionnaire')
set(gca,'XTick',[1:8],'XTickLabel',{'Discomfort','Disorientation','Nausea','Cycling realism','Visual deviation','Muscle fatigue','Disturbances','Control Uniformity'}); 
ylabel('Score(%)') 
ylim([0 100])
